# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json

exclude: __generated__|.changeset|pnpm-lock.yaml|dist|.devcontainer/devcontainer-lock.json
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.1
    hooks:
      - id: check-json5
  - repo: local
    hooks:
      - id: oxc-format-and-lint
        name: oxfmt + oxlint
        entry: bash ./.github/hooks/scripts/pre-commit-oxc.sh
        language: system
        pass_filenames: true
        files: \.(js|jsx|cjs|mjs|ts|tsx|cts|mts|json|md|markdown|graphql|gql|yml|yaml)$
