# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: 'GitHub Action for Cloudflare Pages'
description: 'Deploy to Cloudflare Pages'
inputs:
  apiToken:
    description: 'Cloudflare API Token'
    required: true
  accountId:
    description: 'Cloudflare Account ID'
    required: true
  projectName:
    description: 'The name of the Pages project to upload to'
    required: true
  directory:
    description: 'The directory of static files to upload'
    required: true
  githubToken:
    description: 'Github API key'
    required: true

outputs:
  id:
    description: 'Cloudflare Pages deployed id'
  url:
    description: 'Cloudflare Pages deployed url'
  environment:
    description: 'Cloudflare Pages deployed environment "production" or "preview"'
  alias:
    description: 'Cloudflare Pages deployed alias. Fallsback to deployed url if deployed alias is null'

runs:
  using: 'node16'
  main: 'dist/index.js'
