# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: 'GitHub Action for Cloudflare Pages'
description: 'Deploy to Cloudflare Pages'
branding:
  icon: 'upload-cloud'
  color: 'orange'
inputs:
  api-token:
    description: 'Cloudflare API Token'
    required: true
  account-id:
    description: 'Cloudflare Account ID'
    required: true
  project-name:
    description: 'The name of the Pages project to upload to'
    required: true
  directory:
    description: 'The directory of static files to upload'
    required: true
  github-token:
    description: 'Github API key'
    required: true
  github-environment:
    description: 'The name of the GitHub environment to deploy to. You need to manually create this on github.com'
    required: true

outputs:
  id:
    description: 'Cloudflare Pages deployed id'
    value: ${{ steps.action.outputs.id }}
  url:
    description: 'Cloudflare Pages deployed url'
    value: ${{ steps.action.outputs.url }}
  environment:
    description: 'Cloudflare Pages deployed environment "production" or "preview"'
    value: ${{ steps.action.outputs.environment }}
  alias:
    description: 'Cloudflare Pages deployed alias. Fallsback to deployed url if deployed alias is null'
    value: ${{ steps.action.outputs.alias }}

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: '18'
    - name: Action
      id: action
      run: node ${{ github.action_path }}/dist/index.js
      shell: ${{ (runner.os == 'Windows' && 'pwsh') || 'bash' }}
      env:
        INPUT_API_TOKEN: ${{ inputs.api-token }}
        INPUT_ACCOUNT_ID: ${{ inputs.account-id }}
        INPUT_PROJECT_NAME: ${{ inputs.project-name }}
        INPUT_DIRECTORY: ${{ inputs.directory }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_GITHUB_ENVIRONMENT: ${{ inputs.github-environment }}
