# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: 'GitHub Action for Cloudflare Pages'
description: 'Deploy to Cloudflare Pages'
branding:
  icon: 'upload-cloud'
  color: 'orange'
inputs:
  cloudflare-api-token:
    description: 'Cloudflare API Token'
    required: true
  cloudflare-account-id:
    description: 'Cloudflare Account ID'
    required: true
  cloudflare-project-name:
    description: 'Cloudflare Pages project name to upload to'
    required: true
  directory:
    description: 'Directory of static files to upload'
    required: true
  github-token:
    description: 'Github API key'
    required: true
  github-environment:
    description: 'GitHub environment to deploy to. You need to manually create this for the github repo'
    required: true

outputs:
  id:
    description: 'Cloudflare Pages deployed id'
    value: ${{ steps.action.outputs.id }}
  url:
    description: 'Cloudflare Pages deployed url'
    value: ${{ steps.action.outputs.url }}
  environment:
    description: 'Cloudflare Pages deployed environment "production" or "preview"'
    value: ${{ steps.action.outputs.environment }}
  alias:
    description: 'Cloudflare Pages deployed alias. Fallsback to deployed url if deployed alias is null'
    value: ${{ steps.action.outputs.alias }}

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3.8.0
      with:
        node-version: 18
    - name: Action
      id: action
      run: node ${{ github.action_path }}/dist/index.js
      shell: ${{ (runner.os == 'Windows' && 'pwsh') || 'bash' }}
      env:
        INPUT_CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare-api-token }}
        INPUT_CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare-account-id }}
        INPUT_CLOUDFLARE_PROJECT_NAME: ${{ inputs.cloudflare-project-name }}
        INPUT_DIRECTORY: ${{ inputs.directory }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_GITHUB_ENVIRONMENT: ${{ inputs.github-environment }}
