# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Cloudflare Pages Deploy

on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch
jobs:
  deploy:
    permissions:
      actions: read # Only required for private GitHub Repo
      contents: read
      deployments: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@v4
      - name: 'Deploy to Cloudflare Pages'
        uses: andykenward/github-actions-cloudflare-pages@v2.2.0
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-project-name: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-environment: ${{ (github.ref == 'refs/heads/main' && 'production') || 'preview' }}
