/* Generated by `pnpm run codegen:cloudflare`. Do not edit. */
/* Source: cloudflare/api-schemas @ main */

import type * as HttpClient from 'effect/http/HttpClient'
import type * as Schema from 'effect/Schema'

import * as Data from 'effect/Data'
import * as Effect from 'effect/Effect'
import * as HttpClientError from 'effect/http/HttpClientError'
import * as HttpClientRequest from 'effect/http/HttpClientRequest'
import * as HttpClientResponse from 'effect/http/HttpClientResponse'
// non-recursive definitions
export type Pages_messages = ReadonlyArray<
  {
    readonly code: number
    readonly documentation_url?: string
    readonly message: string
    readonly source?: {readonly pointer?: string} & {
      readonly [x: string]: Schema.Json
    }
  } & {readonly [x: string]: Schema.Json}
>
export type Pages_build_config = {
  readonly build_caching?: boolean | null
  readonly build_command?: string | null
  readonly destination_dir?: string | null
  readonly root_dir?: string | null
  readonly web_analytics_tag: string | null
  readonly web_analytics_token: string | null
} & {readonly [x: string]: Schema.Json}
export type Pages_plain_text_env_var =
  | ({readonly type: 'plain_text'; readonly value: string} & {
      readonly [x: string]: Schema.Json
    })
  | null
export type Pages_secret_text_env_var =
  | ({readonly type: 'secret_text'; readonly value: string} & {
      readonly [x: string]: Schema.Json
    })
  | null
export type Pages_stage = {
  readonly ended_on: string | null
  readonly name: 'queued' | 'initialize' | 'clone_repo' | 'build' | 'deploy'
  readonly started_on: string | null
  readonly status:
    | 'success'
    | 'idle'
    | 'active'
    | 'failure'
    | 'canceled'
    | 'skipped'
} & {readonly [x: string]: Schema.Json}
export type Pages_project_name = string
export type Pages_source_config = {
  readonly deployments_enabled: boolean
  readonly owner: string
  readonly owner_id: string
  readonly path_excludes: ReadonlyArray<string>
  readonly path_includes: ReadonlyArray<string>
  readonly pr_comments_enabled: boolean
  readonly preview_branch_excludes: ReadonlyArray<string>
  readonly preview_branch_includes: ReadonlyArray<string>
  readonly preview_deployment_setting: 'all' | 'none' | 'custom'
  readonly production_branch: string
  readonly production_deployments_enabled: boolean
  readonly repo_id: string
  readonly repo_name: string
} & {readonly [x: string]: Schema.Json}
export type Pages_source_type = 'github' | 'gitlab'
export type Pages_api_response_common_failure = {
  readonly errors: ReadonlyArray<
    {
      readonly code: number
      readonly documentation_url?: string
      readonly message: string
      readonly source?: {readonly pointer?: string} & {
        readonly [x: string]: Schema.Json
      }
    } & {readonly [x: string]: Schema.Json}
  >
  readonly messages: Pages_messages
  readonly result: null
  readonly success: false
} & {readonly [x: string]: Schema.Json}
export type Pages_env_vars = {
  readonly [x: string]: Pages_plain_text_env_var | Pages_secret_text_env_var
} | null
export type Pages_source = {
  readonly config: Pages_source_config
  readonly type: Pages_source_type
} & {readonly [x: string]: Schema.Json}
export type Pages_deployment = {
  readonly aliases: ReadonlyArray<string> | null
  readonly build_config: Pages_build_config
  readonly created_on: string
  readonly deployment_trigger: {
    readonly metadata: {
      readonly branch: string
      readonly commit_dirty: boolean
      readonly commit_hash: string
      readonly commit_message: string
    } & {readonly [x: string]: Schema.Json}
    readonly type: 'github:push' | 'ad_hoc' | 'deploy_hook'
  } & {readonly [x: string]: Schema.Json}
  readonly env_vars: Pages_env_vars
  readonly environment: 'preview' | 'production'
  readonly id: string
  readonly is_skipped: boolean
  readonly latest_stage: Pages_stage
  readonly modified_on: string
  readonly project_id: string
  readonly project_name: Pages_project_name
  readonly short_id: string
  readonly skip_reason?:
    | 'commit_message'
    | 'preview_deployments_disabled'
    | 'production_deployments_disabled'
    | 'path_config'
    | 'branch_config'
    | 'pages_to_workers_conversion'
    | 'superseded_queued_build'
  readonly source: Pages_source | null
  readonly stages: ReadonlyArray<Pages_stage>
  readonly url: string
  readonly uses_functions?: boolean | null
} & {readonly [x: string]: Schema.Json}
// schemas
export type PagesDeploymentGetDeploymentsParams = {
  readonly env?: 'production' | 'preview'
  readonly page?: number
  readonly per_page?: number
}
export type PagesDeploymentGetDeployments200 = {
  readonly errors: Pages_messages
  readonly messages: Pages_messages
  readonly success: true
  readonly result_info?: {
    readonly count?: number
    readonly page?: number
    readonly per_page?: number
    readonly total_count?: number
    readonly total_pages?: number
  } & {readonly [x: string]: Schema.Json}
  readonly result: ReadonlyArray<Pages_deployment>
} & {readonly [x: string]: Schema.Json}
export type PagesDeploymentGetDeployments4XX = Pages_api_response_common_failure
export type PagesDeploymentGetDeploymentInfo200 = {
  readonly errors: Pages_messages
  readonly messages: Pages_messages
  readonly success: true
  readonly result: Pages_deployment
} & {readonly [x: string]: Schema.Json}
export type PagesDeploymentGetDeploymentInfo4XX =
  Pages_api_response_common_failure
export type PagesDeploymentDeleteDeploymentParams = {readonly force?: boolean}
export type PagesDeploymentDeleteDeployment200 = {
  readonly errors: Pages_messages
  readonly messages: Pages_messages
  readonly success: true
  readonly result: {readonly [x: string]: Schema.Json} | null
} & {readonly [x: string]: Schema.Json}
export type PagesDeploymentDeleteDeployment4XX =
  Pages_api_response_common_failure

export interface OperationConfig {
  /**
   * Whether or not the response should be included in the value returned from
   * an operation.
   *
   * If set to `true`, a tuple of `[A, HttpClientResponse]` will be returned,
   * where `A` is the success type of the operation.
   *
   * If set to `false`, only the success type of the operation will be returned.
   */
  readonly includeResponse?: boolean | undefined
}

/**
 * A utility type which optionally includes the response in the return result
 * of an operation based upon the value of the `includeResponse` configuration
 * option.
 */
export type WithOptionalResponse<
  A,
  Config extends OperationConfig | undefined
> = Config extends {
  readonly includeResponse: true
}
  ? [A, HttpClientResponse.HttpClientResponse]
  : Config extends {readonly includeResponse?: false | undefined} | undefined
    ? A
    : A | [A, HttpClientResponse.HttpClientResponse]

export const make = (
  httpClient: HttpClient.HttpClient,
  options: {
    readonly transformClient?:
      | ((
          client: HttpClient.HttpClient
        ) => Effect.Effect<HttpClient.HttpClient>)
      | undefined
  } = {}
): CloudflarePages => {
  const unexpectedStatus = (response: HttpClientResponse.HttpClientResponse) =>
    Effect.flatMap(
      Effect.orElseSucceed(response.json, () => 'Unexpected status code'),
      description =>
        Effect.fail(
          new HttpClientError.HttpClientError({
            reason: new HttpClientError.StatusCodeError({
              request: response.request,
              response,
              description:
                typeof description === 'string'
                  ? description
                  : JSON.stringify(description)
            })
          })
        )
    )
  const withResponse =
    <Config extends OperationConfig>(config: Config | undefined) =>
    (
      f: (
        response: HttpClientResponse.HttpClientResponse
      ) => Effect.Effect<any, any>
    ): ((
      request: HttpClientRequest.HttpClientRequest
    ) => Effect.Effect<any, any>) => {
      const withOptionalResponse = (
        config?.includeResponse
          ? (response: HttpClientResponse.HttpClientResponse) =>
              Effect.map(f(response), a => [a, response])
          : (response: HttpClientResponse.HttpClientResponse) => f(response)
      ) as any
      return options?.transformClient
        ? request =>
            Effect.flatMap(
              Effect.flatMap(options.transformClient!(httpClient), client =>
                client.execute(request)
              ),
              withOptionalResponse
            )
        : request =>
            Effect.flatMap(httpClient.execute(request), withOptionalResponse)
    }
  const __encodePathParam = encodeURIComponent
  const __makePathRequest = (
    method: (url: string) => HttpClientRequest.HttpClientRequest,
    parameters: ReadonlyArray<string>,
    getPath: () => string
  ) =>
    Effect.suspend(() => {
      const fail = (description: string, cause?: unknown) =>
        Effect.fail(
          new HttpClientError.HttpClientError({
            reason: new HttpClientError.InvalidUrlError({
              request: method(''),
              cause,
              description
            })
          })
        )
      if (
        parameters.some(
          value => value === '' || /^(?:\.|%2e){1,2}$/i.test(value)
        )
      ) {
        return fail(
          'Path parameters must be non-empty and cannot be dot segments'
        )
      }
      let path: string
      try {
        path = getPath()
      } catch (cause) {
        return fail('Failed to encode path parameter', cause)
      }
      if (path.split('/').some(segment => /^(?:\.|%2e){1,2}$/i.test(segment))) {
        return fail('Request paths cannot contain dot segments')
      }
      return Effect.succeed(method(path))
    })
  const decodeSuccess = <A>(response: HttpClientResponse.HttpClientResponse) =>
    response.json as Effect.Effect<A, HttpClientError.HttpClientError>
  const decodeVoid = (_response: HttpClientResponse.HttpClientResponse) =>
    Effect.void
  const decodeError =
    <Tag extends string, E>(tag: Tag) =>
    (
      response: HttpClientResponse.HttpClientResponse
    ): Effect.Effect<
      never,
      CloudflarePagesError<Tag, E> | HttpClientError.HttpClientError
    > =>
      Effect.flatMap(
        response.json as Effect.Effect<E, HttpClientError.HttpClientError>,
        cause => Effect.fail(CloudflarePagesError(tag, cause, response))
      )
  const onRequest =
    <Config extends OperationConfig>(config: Config | undefined) =>
    (
      successCodes: ReadonlyArray<string>,
      errorCodes?: Record<string, string>
    ) => {
      const cases: any = {orElse: unexpectedStatus}
      for (const code of successCodes) {
        cases[code] = decodeSuccess
      }
      if (errorCodes) {
        for (const [code, tag] of Object.entries(errorCodes)) {
          cases[code] = decodeError(tag)
        }
      }
      if (successCodes.length === 0) {
        cases['2xx'] = decodeVoid
      }
      return withResponse(config)(HttpClientResponse.matchStatus(cases) as any)
    }
  return {
    httpClient,
    pagesDeploymentGetDeployments: (
      accountId,
      projectName,
      options: Parameters<CloudflarePages['pagesDeploymentGetDeployments']>[2]
    ) =>
      __makePathRequest(
        HttpClientRequest.get,
        [accountId, projectName],
        () =>
          '/accounts/' +
          __encodePathParam(accountId) +
          '/pages/projects/' +
          __encodePathParam(projectName) +
          '/deployments'
      ).pipe(
        Effect.flatMap(request =>
          request.pipe(
            HttpClientRequest.setUrlParams({
              env: options?.params?.['env'] as any,
              page: options?.params?.['page'] as any,
              per_page: options?.params?.['per_page'] as any
            }),
            onRequest(options?.config)(['2xx'], {
              '4xx': 'PagesDeploymentGetDeployments4XX'
            })
          )
        )
      ),
    pagesDeploymentGetDeploymentInfo: (
      accountId,
      projectName,
      deploymentId,
      options: Parameters<
        CloudflarePages['pagesDeploymentGetDeploymentInfo']
      >[3]
    ) =>
      __makePathRequest(
        HttpClientRequest.get,
        [accountId, projectName, deploymentId],
        () =>
          '/accounts/' +
          __encodePathParam(accountId) +
          '/pages/projects/' +
          __encodePathParam(projectName) +
          '/deployments/' +
          __encodePathParam(deploymentId) +
          ''
      ).pipe(
        Effect.flatMap(request =>
          request.pipe(
            onRequest(options?.config)(['2xx'], {
              '4xx': 'PagesDeploymentGetDeploymentInfo4XX'
            })
          )
        )
      ),
    pagesDeploymentDeleteDeployment: (
      accountId,
      projectName,
      deploymentId,
      options: Parameters<CloudflarePages['pagesDeploymentDeleteDeployment']>[3]
    ) =>
      __makePathRequest(
        HttpClientRequest.delete,
        [accountId, projectName, deploymentId],
        () =>
          '/accounts/' +
          __encodePathParam(accountId) +
          '/pages/projects/' +
          __encodePathParam(projectName) +
          '/deployments/' +
          __encodePathParam(deploymentId) +
          ''
      ).pipe(
        Effect.flatMap(request =>
          request.pipe(
            HttpClientRequest.setUrlParams({
              force: options?.params?.['force'] as any
            }),
            onRequest(options?.config)(['2xx'], {
              '4xx': 'PagesDeploymentDeleteDeployment4XX'
            })
          )
        )
      )
  }
}

export interface CloudflarePages {
  readonly httpClient: HttpClient.HttpClient
  /**
   * List the production or preview deployments for a Cloudflare Pages project.
   */
  readonly pagesDeploymentGetDeployments: {
    <Config extends OperationConfig | undefined = undefined>(
      accountId: string,
      projectName: string,
      options: {
        readonly params?: PagesDeploymentGetDeploymentsParams | undefined
        readonly config: Config
      }
    ): Effect.Effect<
      WithOptionalResponse<PagesDeploymentGetDeployments200, Config>,
      | HttpClientError.HttpClientError
      | CloudflarePagesError<
          'PagesDeploymentGetDeployments4XX',
          PagesDeploymentGetDeployments4XX
        >
    >
    <Config extends OperationConfig | undefined = undefined>(
      accountId: string,
      projectName: string,
      options:
        | {
            readonly params?: PagesDeploymentGetDeploymentsParams | undefined
            readonly config?: Config | undefined
          }
        | undefined
    ): Effect.Effect<
      WithOptionalResponse<
        PagesDeploymentGetDeployments200,
        Config | undefined
      >,
      | HttpClientError.HttpClientError
      | CloudflarePagesError<
          'PagesDeploymentGetDeployments4XX',
          PagesDeploymentGetDeployments4XX
        >
    >
  }
  /**
   * Retrieve the status and details of a Cloudflare Pages deployment.
   */
  readonly pagesDeploymentGetDeploymentInfo: {
    <Config extends OperationConfig | undefined = undefined>(
      accountId: string,
      projectName: string,
      deploymentId: string,
      options: {readonly config: Config}
    ): Effect.Effect<
      WithOptionalResponse<PagesDeploymentGetDeploymentInfo200, Config>,
      | HttpClientError.HttpClientError
      | CloudflarePagesError<
          'PagesDeploymentGetDeploymentInfo4XX',
          PagesDeploymentGetDeploymentInfo4XX
        >
    >
    <Config extends OperationConfig | undefined = undefined>(
      accountId: string,
      projectName: string,
      deploymentId: string,
      options: {readonly config?: Config | undefined} | undefined
    ): Effect.Effect<
      WithOptionalResponse<
        PagesDeploymentGetDeploymentInfo200,
        Config | undefined
      >,
      | HttpClientError.HttpClientError
      | CloudflarePagesError<
          'PagesDeploymentGetDeploymentInfo4XX',
          PagesDeploymentGetDeploymentInfo4XX
        >
    >
  }
  /**
   * Remove a deployment from a Cloudflare Pages project.
   */
  readonly pagesDeploymentDeleteDeployment: {
    <Config extends OperationConfig | undefined = undefined>(
      accountId: string,
      projectName: string,
      deploymentId: string,
      options: {
        readonly params?: PagesDeploymentDeleteDeploymentParams | undefined
        readonly config: Config
      }
    ): Effect.Effect<
      WithOptionalResponse<PagesDeploymentDeleteDeployment200, Config>,
      | HttpClientError.HttpClientError
      | CloudflarePagesError<
          'PagesDeploymentDeleteDeployment4XX',
          PagesDeploymentDeleteDeployment4XX
        >
    >
    <Config extends OperationConfig | undefined = undefined>(
      accountId: string,
      projectName: string,
      deploymentId: string,
      options:
        | {
            readonly params?: PagesDeploymentDeleteDeploymentParams | undefined
            readonly config?: Config | undefined
          }
        | undefined
    ): Effect.Effect<
      WithOptionalResponse<
        PagesDeploymentDeleteDeployment200,
        Config | undefined
      >,
      | HttpClientError.HttpClientError
      | CloudflarePagesError<
          'PagesDeploymentDeleteDeployment4XX',
          PagesDeploymentDeleteDeployment4XX
        >
    >
  }
}

export interface CloudflarePagesError<Tag extends string, E> {
  readonly _tag: Tag
  readonly request: HttpClientRequest.HttpClientRequest
  readonly response: HttpClientResponse.HttpClientResponse
  readonly cause: E
}

class CloudflarePagesErrorImpl extends Data.Error<{
  _tag: string
  cause: any
  request: HttpClientRequest.HttpClientRequest
  response: HttpClientResponse.HttpClientResponse
}> {}

export const CloudflarePagesError = <Tag extends string, E>(
  tag: Tag,
  cause: E,
  response: HttpClientResponse.HttpClientResponse
): CloudflarePagesError<Tag, E> =>
  new CloudflarePagesErrorImpl({
    _tag: tag,
    cause,
    response,
    request: response.request
  }) as any
