/* eslint-disable */
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
import type { DocumentTypeDecoration } from '@graphql-typed-document-node/core';
/** Autogenerated input type of AddComment */
export type AddCommentInput = {
  /** The contents of the comment. */
  readonly body: string;
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: string | null | undefined;
  /** The Node ID of the subject to modify. */
  readonly subjectId: string | number;
};

/** Autogenerated input type of CreateDeployment */
export type CreateDeploymentInput = {
  /** Attempt to automatically merge the default branch into the requested ref, defaults to true. */
  readonly autoMerge?: boolean | null | undefined;
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: string | null | undefined;
  /** Short description of the deployment. */
  readonly description?: string | null | undefined;
  /** Name for the target deployment environment. */
  readonly environment?: string | null | undefined;
  /** JSON payload with extra information about the deployment. */
  readonly payload?: string | null | undefined;
  /** The node ID of the ref to be deployed. */
  readonly refId: string | number;
  /** The node ID of the repository. */
  readonly repositoryId: string | number;
  /**
   * The status contexts to verify against commit status checks. To bypass required
   * contexts, pass an empty array. Defaults to all unique contexts.
   */
  readonly requiredContexts?: ReadonlyArray<string> | null | undefined;
  /** Specifies a task to execute. */
  readonly task?: string | null | undefined;
};

/** Autogenerated input type of CreateDeploymentStatus */
export type CreateDeploymentStatusInput = {
  /**
   * Adds a new inactive status to all non-transient, non-production environment
   * deployments with the same repository and environment name as the created
   * status's deployment.
   */
  readonly autoInactive?: boolean | null | undefined;
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: string | null | undefined;
  /** The node ID of the deployment. */
  readonly deploymentId: string | number;
  /** A short description of the status. Maximum length of 140 characters. */
  readonly description?: string | null | undefined;
  /** If provided, updates the environment of the deploy. Otherwise, does not modify the environment. */
  readonly environment?: string | null | undefined;
  /** Sets the URL for accessing your environment. */
  readonly environmentUrl?: string | null | undefined;
  /**
   * The log URL to associate with this status.       This URL should contain
   * output to keep the user updated while the task is running       or serve as
   * historical information for what happened in the deployment.
   */
  readonly logUrl?: string | null | undefined;
  /** The state of the deployment. */
  readonly state: DeploymentStatusState;
};

/** Autogenerated input type of DeleteDeployment */
export type DeleteDeploymentInput = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: string | null | undefined;
  /** The Node ID of the deployment to be deleted. */
  readonly id: string | number;
};

/** Autogenerated input type of DeleteIssueComment */
export type DeleteIssueCommentInput = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: string | null | undefined;
  /** The ID of the comment to delete. */
  readonly id: string | number;
};

/** The possible states for a deployment status. */
export enum DeploymentStatusState {
  /** The deployment experienced an error. */
  Error = 'ERROR',
  /** The deployment has failed. */
  Failure = 'FAILURE',
  /** The deployment is inactive. */
  Inactive = 'INACTIVE',
  /** The deployment is in progress. */
  InProgress = 'IN_PROGRESS',
  /** The deployment is pending. */
  Pending = 'PENDING',
  /** The deployment is queued */
  Queued = 'QUEUED',
  /** The deployment was successful. */
  Success = 'SUCCESS',
  /** The deployment is waiting. */
  Waiting = 'WAITING'
}

export type ListPayloadExampleFilesQueryVariables = Exact<{
  owner: string;
  repo: string;
  path: string;
}>;


export type ListPayloadExampleFilesQuery = { readonly repository: { readonly object:
      | { readonly __typename: 'Blob' }
      | { readonly __typename: 'Commit' }
      | { readonly __typename: 'Tag' }
      | { readonly __typename: 'Tree', readonly entries: ReadonlyArray<{ readonly name: string, readonly type: string, readonly language: { readonly name: string } | null, readonly object:
            | { readonly __typename: 'Blob', readonly text: string | null }
            | { readonly __typename: 'Commit' }
            | { readonly __typename: 'Tag' }
            | { readonly __typename: 'Tree' }
           | null }> | null }
     | null } | null };

export type GetLatestReleaseQueryVariables = Exact<{
  owner: string;
  repo: string;
}>;


export type GetLatestReleaseQuery = { readonly repository: { readonly latestRelease: { readonly tagName: string, readonly tagCommit: { readonly oid: string } | null } | null } | null };

export type AddPullRequestCommentMutationVariables = Exact<{
  input: AddCommentInput;
}>;


export type AddPullRequestCommentMutation = { readonly addComment: { readonly commentEdge: { readonly node: { readonly id: string } | null } | null } | null };

export type GetPullRequestIdQueryVariables = Exact<{
  owner: string;
  repo: string;
  number: number;
}>;


export type GetPullRequestIdQuery = { readonly repository: { readonly pullRequest: { readonly id: string } | null } | null };

export type GetOpenPullRequestByBranchQueryVariables = Exact<{
  owner: string;
  repo: string;
  headRefName: string;
}>;


export type GetOpenPullRequestByBranchQuery = { readonly repository: { readonly pullRequests: { readonly nodes: ReadonlyArray<{ readonly id: string } | null> | null } } | null };

export type CreateGitHubDeploymentMutationVariables = Exact<{
  input: CreateDeploymentInput;
}>;


export type CreateGitHubDeploymentMutation = { readonly createDeployment: { readonly deployment: { readonly id: string } | null } | null };

export type CreateGitHubDeploymentStatusMutationVariables = Exact<{
  input: CreateDeploymentStatusInput;
}>;


export type CreateGitHubDeploymentStatusMutation = { readonly createDeploymentStatus: { readonly clientMutationId: string | null } | null };

export type DeactivateAndDeleteGitHubDeploymentMutationVariables = Exact<{
  status: CreateDeploymentStatusInput;
  deployment: DeleteDeploymentInput;
}>;


export type DeactivateAndDeleteGitHubDeploymentMutation = { readonly createDeploymentStatus: { readonly clientMutationId: string | null } | null, readonly deleteDeployment: { readonly clientMutationId: string | null } | null };

export type DeactivateAndDeleteGitHubDeploymentAndCommentMutationVariables = Exact<{
  status: CreateDeploymentStatusInput;
  deployment: DeleteDeploymentInput;
  comment: DeleteIssueCommentInput;
}>;


export type DeactivateAndDeleteGitHubDeploymentAndCommentMutation = { readonly createDeploymentStatus: { readonly clientMutationId: string | null } | null, readonly deleteDeployment: { readonly clientMutationId: string | null } | null, readonly deleteIssueComment: { readonly clientMutationId: string | null } | null };

export type GetEnvironmentAndRefQueryVariables = Exact<{
  owner: string;
  repo: string;
  environmentName: string;
  qualifiedName: string;
}>;


export type GetEnvironmentAndRefQuery = { readonly repository: { readonly environment: { readonly id: string, readonly name: string } | null, readonly ref: { readonly id: string } | null } | null };

export class TypedDocumentString<TResult, TVariables>
  extends String
  implements DocumentTypeDecoration<TResult, TVariables>
{
  __apiType?: NonNullable<DocumentTypeDecoration<TResult, TVariables>['__apiType']>;
  private value: string;
  public __meta__?: Record<string, any> | undefined;

  constructor(value: string, __meta__?: Record<string, any> | undefined) {
    super(value);
    this.value = value;
    this.__meta__ = __meta__;
  }

  override toString(): string & DocumentTypeDecoration<TResult, TVariables> {
    return this.value;
  }
}

export const ListPayloadExampleFilesDocument = new TypedDocumentString(`
    query ListPayloadExampleFiles($owner: String!, $repo: String!, $path: String!) {
  repository(owner: $owner, name: $repo) {
    object(expression: $path) {
      __typename
      ... on Tree {
        entries {
          name
          type
          language {
            name
          }
          object {
            __typename
            ... on Blob {
              text
            }
          }
        }
      }
    }
  }
}
    `) as unknown as TypedDocumentString<ListPayloadExampleFilesQuery, ListPayloadExampleFilesQueryVariables>;
export const GetLatestReleaseDocument = new TypedDocumentString(`
    query GetLatestRelease($owner: String!, $repo: String!) {
  repository(owner: $owner, name: $repo) {
    latestRelease {
      tagName
      tagCommit {
        oid
      }
    }
  }
}
    `) as unknown as TypedDocumentString<GetLatestReleaseQuery, GetLatestReleaseQueryVariables>;
export const AddPullRequestCommentDocument = new TypedDocumentString(`
    mutation AddPullRequestComment($input: AddCommentInput!) {
  addComment(input: $input) {
    commentEdge {
      node {
        id
      }
    }
  }
}
    `) as unknown as TypedDocumentString<AddPullRequestCommentMutation, AddPullRequestCommentMutationVariables>;
export const GetPullRequestIdDocument = new TypedDocumentString(`
    query GetPullRequestId($owner: String!, $repo: String!, $number: Int!) {
  repository(owner: $owner, name: $repo) {
    pullRequest(number: $number) {
      id
    }
  }
}
    `) as unknown as TypedDocumentString<GetPullRequestIdQuery, GetPullRequestIdQueryVariables>;
export const GetOpenPullRequestByBranchDocument = new TypedDocumentString(`
    query GetOpenPullRequestByBranch($owner: String!, $repo: String!, $headRefName: String!) {
  repository(owner: $owner, name: $repo) {
    pullRequests(first: 1, states: [OPEN], headRefName: $headRefName) {
      nodes {
        id
      }
    }
  }
}
    `) as unknown as TypedDocumentString<GetOpenPullRequestByBranchQuery, GetOpenPullRequestByBranchQueryVariables>;
export const CreateGitHubDeploymentDocument = new TypedDocumentString(`
    mutation CreateGitHubDeployment($input: CreateDeploymentInput!) {
  createDeployment(input: $input) {
    deployment {
      id
    }
  }
}
    `) as unknown as TypedDocumentString<CreateGitHubDeploymentMutation, CreateGitHubDeploymentMutationVariables>;
export const CreateGitHubDeploymentStatusDocument = new TypedDocumentString(`
    mutation CreateGitHubDeploymentStatus($input: CreateDeploymentStatusInput!) {
  createDeploymentStatus(input: $input) {
    clientMutationId
  }
}
    `) as unknown as TypedDocumentString<CreateGitHubDeploymentStatusMutation, CreateGitHubDeploymentStatusMutationVariables>;
export const DeactivateAndDeleteGitHubDeploymentDocument = new TypedDocumentString(`
    mutation DeactivateAndDeleteGitHubDeployment($status: CreateDeploymentStatusInput!, $deployment: DeleteDeploymentInput!) {
  createDeploymentStatus(input: $status) {
    clientMutationId
  }
  deleteDeployment(input: $deployment) {
    clientMutationId
  }
}
    `) as unknown as TypedDocumentString<DeactivateAndDeleteGitHubDeploymentMutation, DeactivateAndDeleteGitHubDeploymentMutationVariables>;
export const DeactivateAndDeleteGitHubDeploymentAndCommentDocument = new TypedDocumentString(`
    mutation DeactivateAndDeleteGitHubDeploymentAndComment($status: CreateDeploymentStatusInput!, $deployment: DeleteDeploymentInput!, $comment: DeleteIssueCommentInput!) {
  createDeploymentStatus(input: $status) {
    clientMutationId
  }
  deleteDeployment(input: $deployment) {
    clientMutationId
  }
  deleteIssueComment(input: $comment) {
    clientMutationId
  }
}
    `) as unknown as TypedDocumentString<DeactivateAndDeleteGitHubDeploymentAndCommentMutation, DeactivateAndDeleteGitHubDeploymentAndCommentMutationVariables>;
export const GetEnvironmentAndRefDocument = new TypedDocumentString(`
    query GetEnvironmentAndRef($owner: String!, $repo: String!, $environmentName: String!, $qualifiedName: String!) {
  repository(owner: $owner, name: $repo) {
    environment(name: $environmentName) {
      id
      name
    }
    ref(qualifiedName: $qualifiedName) {
      id
    }
  }
}
    `) as unknown as TypedDocumentString<GetEnvironmentAndRefQuery, GetEnvironmentAndRefQueryVariables>;