/* Generated by `pnpm run codegen:cloudflare`. Do not edit. */
/* Source: cloudflare/api-schemas @ main */
export interface paths {
  '/accounts/{account_id}/pages/projects/{project_name}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get project
     * @description Fetch a project by name.
     */
    get: operations['pages-project-get-project']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/accounts/{account_id}/pages/projects/{project_name}/deployments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get deployments
     * @description Fetch a list of project deployments.
     */
    get: operations['pages-deployment-get-deployments']
    put?: never
    /**
     * Create deployment
     * @description Start a new deployment from production. The repository and account must have already been authorized on the Cloudflare Pages dashboard.
     */
    post: operations['pages-deployment-create-deployment']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/accounts/{account_id}/pages/projects/{project_name}/deployments/{deployment_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get deployment info
     * @description Fetch information about a deployment.
     */
    get: operations['pages-deployment-get-deployment-info']
    put?: never
    post?: never
    /**
     * Delete deployment
     * @description Delete a deployment.
     */
    delete: operations['pages-deployment-delete-deployment']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * @description Name of the project.
     * @example this-is-my-project-01
     */
    pages_project_name: string
    /**
     * @description Identifier.
     * @example 023e105f4ecef8ad9ca31a8372d0c353
     */
    pages_identifier: string
    'pages_api-response-common': {
      errors: components['schemas']['pages_messages']
      messages: components['schemas']['pages_messages']
      /**
       * @description Whether the API call was successful.
       * @example true
       * @enum {boolean}
       */
      success: true
    }
    /** @example [] */
    pages_messages: {
      code: number
      documentation_url?: string
      message: string
      source?: {
        pointer?: string
      }
    }[]
    pages_project: {
      build_config?: components['schemas']['pages_build_config']
      canonical_deployment: components['schemas']['pages_deployment'] &
        (Record<string, never> | null)
      /**
       * Format: date-time
       * @description When the project was created.
       * @example 2017-01-01T00:00:00Z
       */
      readonly created_on: string
      /** @description Configs for deployments in a project. */
      deployment_configs: {
        /** @description Configs for preview deploys. */
        preview: components['schemas']['pages_deployment_config_values']
        /** @description Configs for production deploys. */
        production: components['schemas']['pages_deployment_config_values']
      }
      /**
       * @description A list of associated custom domains for the project.
       * @example [
       *       "customdomain.com",
       *       "customdomain.org"
       *     ]
       */
      readonly domains?: string[]
      /** @description Framework the project is using. */
      readonly framework: string
      /** @description Version of the framework the project is using. */
      readonly framework_version: string
      /**
       * @description ID of the project.
       * @example 7b162ea7-7367-4d67-bcde-1160995d5
       */
      readonly id: string
      latest_deployment: components['schemas']['pages_deployment'] &
        (Record<string, never> | null)
      name: components['schemas']['pages_project_name']
      /**
       * @description Name of the preview script.
       * @example pages-worker--1234567-preview
       */
      readonly preview_script_name: string
      /**
       * @description Production branch of the project. Used to identify production deployments.
       * @example main
       */
      production_branch: string
      /**
       * @description Name of the production script.
       * @example pages-worker--1234567-production
       */
      readonly production_script_name: string
      source?: components['schemas']['pages_source']
      /**
       * @description The Cloudflare subdomain associated with the project.
       * @example helloworld.pages.dev
       */
      readonly subdomain?: string
      /** @description Whether the project uses functions. */
      readonly uses_functions: boolean | null
    }
    /** @description Configs for the project build process. */
    pages_build_config: {
      /**
       * @description Enable build caching for the project.
       * @example true
       */
      build_caching?: boolean | null
      /**
       * @description Command used to build project.
       * @example npm run build
       */
      build_command?: string | null
      /**
       * @description Assets output directory of the build.
       * @example build
       */
      destination_dir?: string | null
      /**
       * @description Directory to run the command.
       * @example /
       */
      root_dir?: string | null
      /**
       * @description The classifying tag for analytics.
       * @example cee1c73f6e4743d0b5e6bb1a0bcaabcc
       */
      web_analytics_tag: string | null
      /**
       * @description The auth token for analytics.
       * @example 021e1057c18547eca7b79f2516f06o7x
       */
      web_analytics_token: string | null
    }
    pages_deployment: {
      /**
       * @description A list of alias URLs pointing to this deployment.
       * @example [
       *       "https://branchname.projectname.pages.dev"
       *     ]
       */
      readonly aliases: string[] | null
      build_config: components['schemas']['pages_build_config']
      /**
       * Format: date-time
       * @description When the deployment was created.
       * @example 2021-03-09T00:55:03.923456Z
       */
      readonly created_on: string
      /** @description Info about what caused the deployment. */
      readonly deployment_trigger: {
        /** @description Additional info about the trigger. */
        metadata: {
          /**
           * @description Where the trigger happened.
           * @example main
           */
          branch: string
          /**
           * @description Whether the deployment trigger commit was dirty.
           * @example false
           */
          commit_dirty: boolean
          /**
           * @description Hash of the deployment trigger commit.
           * @example ad9ccd918a81025731e10e40267e11273a263421
           */
          commit_hash: string
          /**
           * @description Message of the deployment trigger commit.
           * @example Update index.html
           */
          commit_message: string
        }
        /**
         * @description What caused the deployment.
         * @example ad_hoc
         * @enum {string}
         */
        type: 'github:push' | 'ad_hoc' | 'deploy_hook'
      }
      env_vars: components['schemas']['pages_env_vars']
      /**
       * @description Type of deploy.
       * @example preview
       * @enum {string}
       */
      readonly environment: 'preview' | 'production'
      /**
       * @description Id of the deployment.
       * @example f64788e9-fccd-4d4a-a28a-cb84f88f6
       */
      readonly id: string
      /**
       * @description If the deployment has been skipped.
       * @example true
       */
      readonly is_skipped: boolean
      latest_stage: components['schemas']['pages_stage']
      /**
       * Format: date-time
       * @description When the deployment was last modified.
       * @example 2021-03-09T00:58:59.045655
       */
      readonly modified_on: string
      /**
       * @description Id of the project.
       * @example 7b162ea7-7367-4d67-bcde-1160995d5
       */
      readonly project_id: string
      project_name: components['schemas']['pages_project_name']
      /**
       * @description Short Id (8 character) of the deployment.
       * @example f64788e9
       */
      readonly short_id: string
      source: components['schemas']['pages_source']
      /**
       * @description List of past stages.
       * @example [
       *       {
       *         "ended_on": "2021-06-03T15:39:03.134378Z",
       *         "name": "queued",
       *         "started_on": "2021-06-03T15:38:15.608194Z",
       *         "status": "active"
       *       },
       *       {
       *         "ended_on": null,
       *         "name": "initialize",
       *         "started_on": null,
       *         "status": "idle"
       *       },
       *       {
       *         "ended_on": null,
       *         "name": "clone_repo",
       *         "started_on": null,
       *         "status": "idle"
       *       },
       *       {
       *         "ended_on": null,
       *         "name": "build",
       *         "started_on": null,
       *         "status": "idle"
       *       },
       *       {
       *         "ended_on": null,
       *         "name": "deploy",
       *         "started_on": null,
       *         "status": "idle"
       *       }
       *     ]
       */
      readonly stages: components['schemas']['pages_stage'][]
      /**
       * @description The live URL to view this deployment.
       * @example https://f64788e9.ninjakittens.pages.dev
       */
      readonly url: string
      /** @description Whether the deployment uses functions. */
      readonly uses_functions?: boolean | null
    }
    /** @description Environment variables used for builds and Pages Functions. */
    pages_env_vars: {
      [key: string]:
        | (
            | components['schemas']['pages_plain_text_env_var']
            | components['schemas']['pages_secret_text_env_var']
          )
        | null
    } | null
    /**
     * @description A plaintext environment variable.
     * @example {
     *       "type": "plain_text",
     *       "value": "hello world"
     *     }
     */
    pages_plain_text_env_var: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'plain_text'
      /** @description Environment variable value. */
      value: string
    } | null
    /**
     * @description An encrypted environment variable.
     * @example {
     *       "type": "secret_text",
     *       "value": ""
     *     }
     */
    pages_secret_text_env_var: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'secret_text'
      /** @description Secret value. */
      value: string
    } | null
    /** @description The status of the deployment. */
    pages_stage: {
      /**
       * Format: date-time
       * @description When the stage ended.
       * @example 2021-03-09T00:58:59.045655
       */
      readonly ended_on: string | null
      /**
       * @description The current build stage.
       * @example deploy
       * @enum {string}
       */
      name: 'queued' | 'initialize' | 'clone_repo' | 'build' | 'deploy'
      /**
       * Format: date-time
       * @description When the stage started.
       * @example 2021-03-09T00:55:03.923456Z
       */
      readonly started_on: string | null
      /**
       * @description State of the current stage.
       * @example success
       * @enum {string}
       */
      readonly status: 'success' | 'idle' | 'active' | 'failure' | 'canceled'
    }
    /** @description Configs for the project source control. */
    pages_source: {
      config: {
        /**
         * @deprecated
         * @description Whether to enable automatic deployments when pushing to the source repository.
         *     When disabled, no deployments (production or preview) will be triggered automatically.
         */
        deployments_enabled: boolean
        /**
         * @description The owner of the repository.
         * @example my-org
         */
        owner: string
        /**
         * @description The owner ID of the repository.
         * @example 12345678
         */
        owner_id: string
        /** @description A list of paths that should be excluded from triggering a preview deployment. Wildcard syntax (`*`) is supported. */
        path_excludes: string[]
        /** @description A list of paths that should be watched to trigger a preview deployment. Wildcard syntax (`*`) is supported. */
        path_includes: string[]
        /** @description Whether to enable PR comments. */
        pr_comments_enabled: boolean
        /** @description A list of branches that should not trigger a preview deployment. Wildcard syntax (`*`) is supported. Must be used with `preview_deployment_setting` set to `custom`. */
        preview_branch_excludes: string[]
        /** @description A list of branches that should trigger a preview deployment. Wildcard syntax (`*`) is supported. Must be used with `preview_deployment_setting` set to `custom`. */
        preview_branch_includes: string[]
        /**
         * @description Controls whether commits to preview branches trigger a preview deployment.
         * @enum {string}
         */
        preview_deployment_setting: 'all' | 'none' | 'custom'
        /**
         * @description The production branch of the repository.
         * @example main
         */
        production_branch: string
        /** @description Whether to trigger a production deployment on commits to the production branch. */
        production_deployments_enabled: boolean
        /**
         * @description The ID of the repository.
         * @example 12345678
         */
        repo_id: string
        /**
         * @description The name of the repository.
         * @example my-repo
         */
        repo_name: string
      }
      /**
       * @description The source control management provider.
       * @example github
       * @enum {string}
       */
      type: 'github' | 'gitlab'
    }
    pages_deployment_config_values: {
      /**
       * @description Constellation bindings used for Pages Functions.
       * @example {
       *       "AI_BINDING": {
       *         "project_id": "some-project-id"
       *       }
       *     }
       */
      ai_bindings?: {
        [key: string]: {
          project_id: string
        }
      }
      /**
       * @description Whether to always use the latest compatibility date for Pages Functions.
       * @example false
       */
      always_use_latest_compatibility_date: boolean
      /**
       * @description Analytics Engine bindings used for Pages Functions.
       * @example {
       *       "ANALYTICS_ENGINE_BINDING": {
       *         "dataset": "api_analytics"
       *       }
       *     }
       */
      analytics_engine_datasets?: {
        [key: string]: {
          /**
           * @description Name of the dataset.
           * @example api_analytics
           */
          dataset: string
        }
      }
      /**
       * @description Browser bindings used for Pages Functions.
       * @example {
       *       "BROWSER": {}
       *     }
       */
      browsers?: {
        [key: string]: Record<string, never> | null
      }
      /**
       * @description The major version of the build image to use for Pages Functions.
       * @example 3
       */
      build_image_major_version: number
      /**
       * @description Compatibility date used for Pages Functions.
       * @example 2025-01-01
       */
      compatibility_date: string
      /**
       * @description Compatibility flags used for Pages Functions.
       * @example [
       *       "url_standard"
       *     ]
       */
      compatibility_flags: string[]
      /**
       * @description D1 databases used for Pages Functions.
       * @example {
       *       "D1_BINDING": {
       *         "id": "445e2955-951a-43f8-a35b-a4d0c8138f63"
       *       }
       *     }
       */
      d1_databases?: {
        [key: string]: {
          /**
           * @description UUID of the D1 database.
           * @example 445e2955-951a-43f8-a35b-a4d0c8138f63
           */
          id: string
        }
      }
      /**
       * @description Durable Object namespaces used for Pages Functions.
       * @example {
       *       "DO_BINDING": {
       *         "namespace_id": "5eb63bbbe01eeed093cb22bb8f5acdc3"
       *       }
       *     }
       */
      durable_object_namespaces?: {
        [key: string]: {
          /**
           * @description ID of the Durable Object namespace.
           * @example 5eb63bbbe01eeed093cb22bb8f5acdc3
           */
          namespace_id: string
        }
      }
      env_vars: components['schemas']['pages_env_vars']
      /**
       * @description Whether to fail open when the deployment config cannot be applied.
       * @example true
       */
      fail_open: boolean
      /**
       * @description Hyperdrive bindings used for Pages Functions.
       * @example {
       *       "HYPERDRIVE": {
       *         "id": "a76a99bc342644deb02c38d66082262a"
       *       }
       *     }
       */
      hyperdrive_bindings?: {
        [key: string]: {
          /** @example a76a99bc342644deb02c38d66082262a */
          id: string
        }
      }
      /**
       * @description KV namespaces used for Pages Functions.
       * @example {
       *       "KV_BINDING": {
       *         "namespace_id": "5eb63bbbe01eeed093cb22bb8f5acdc3"
       *       }
       *     }
       */
      kv_namespaces?: {
        [key: string]: {
          /**
           * @description ID of the KV namespace.
           * @example 5eb63bbbe01eeed093cb22bb8f5acdc3
           */
          namespace_id: string
        }
      }
      /**
       * @description Limits for Pages Functions.
       * @example {
       *       "cpu_ms": 100
       *     }
       */
      limits?: {
        /**
         * @description CPU time limit in milliseconds.
         * @example 100
         */
        cpu_ms: number
      }
      /**
       * @description mTLS bindings used for Pages Functions.
       * @example {
       *       "MTLS": {
       *         "certificate_id": "d7cdd17c-916f-4cb7-aabe-585eb382ec4e"
       *       }
       *     }
       */
      mtls_certificates?: {
        [key: string]: {
          /** @example d7cdd17c-916f-4cb7-aabe-585eb382ec4e */
          certificate_id: string
        }
      }
      /**
       * @description Placement setting used for Pages Functions.
       * @example {
       *       "mode": "smart"
       *     }
       */
      placement?: {
        /**
         * @description Placement mode.
         * @example smart
         */
        mode: string
      }
      /**
       * @description Queue Producer bindings used for Pages Functions.
       * @example {
       *       "QUEUE_PRODUCER_BINDING": {
       *         "name": "some-queue"
       *       }
       *     }
       */
      queue_producers?: {
        [key: string]: {
          /**
           * @description Name of the Queue.
           * @example some-queue
           */
          name: string
        }
      }
      /**
       * @description R2 buckets used for Pages Functions.
       * @example {
       *       "R2_BINDING": {
       *         "name": "some-bucket"
       *       }
       *     }
       */
      r2_buckets?: {
        [key: string]: {
          /**
           * @description Jurisdiction of the R2 bucket.
           * @example eu
           */
          jurisdiction?: string | null
          /**
           * @description Name of the R2 bucket.
           * @example some-bucket
           */
          name: string
        }
      }
      /**
       * @description Services used for Pages Functions.
       * @example {
       *       "SERVICE_BINDING": {
       *         "entrypoint": "MyHandler",
       *         "environment": "production",
       *         "service": "example-worker"
       *       }
       *     }
       */
      services?: {
        [key: string]: {
          /** @description The entrypoint to bind to. */
          entrypoint?: string | null
          /** @description The Service environment. */
          environment: string
          /** @description The Service name. */
          service: string
        }
      }
      /**
       * @deprecated
       * @description The usage model for Pages Functions.
       * @example standard
       * @enum {string}
       */
      usage_model: 'standard' | 'bundled' | 'unbound'
      /**
       * @description Vectorize bindings used for Pages Functions.
       * @example {
       *       "VECTORIZE": {
       *         "index_name": "my_index"
       *       }
       *     }
       */
      vectorize_bindings?: {
        [key: string]: {
          /** @example my_index */
          index_name: string
        }
      }
      /**
       * @description Hash of the Wrangler configuration used for the deployment.
       * @example abc123def456
       */
      wrangler_config_hash?: string
    }
    'pages_api-response-common-failure': {
      /**
       * @example [
       *       {
       *         "code": 7003,
       *         "message": "No route for the URI"
       *       }
       *     ]
       */
      errors: components['schemas']['pages_messages']
      /** @example [] */
      messages: components['schemas']['pages_messages']
      /** @enum {object|null} */
      result: never | null
      /**
       * @description Whether the API call was successful.
       * @example false
       * @enum {boolean}
       */
      success: false
    }
    'pages_api-response-collection': components['schemas']['pages_api-response-common'] & {
      result_info?: {
        /**
         * @description Total number of results for the requested service.
         * @example 1
         */
        count?: number
        /**
         * @description Current page within paginated list of results.
         * @example 1
         */
        page?: number
        /**
         * @description Number of results per page of results.
         * @example 20
         */
        per_page?: number
        /**
         * @description Total results available without any search parameters.
         * @example 2000
         */
        total_count?: number
        /**
         * @description The number of total pages in the entire result set.
         * @example 100
         */
        total_pages?: number
      }
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  'pages-project-get-project': {
    parameters: {
      query?: never
      header?: never
      path: {
        project_name: components['schemas']['pages_project_name']
        account_id: components['schemas']['pages_identifier']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Get project response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['pages_api-response-common'] & {
            result: components['schemas']['pages_project']
          }
        }
      }
      /** @description Get project response failure. */
      '4XX': {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['pages_api-response-common-failure']
        }
      }
    }
  }
  'pages-deployment-get-deployments': {
    parameters: {
      query?: {
        env?: 'production' | 'preview'
        page?: number
        per_page?: number
      }
      header?: never
      path: {
        project_name: components['schemas']['pages_project_name']
        account_id: components['schemas']['pages_identifier']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Get deployments response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['pages_api-response-collection'] & {
            result: components['schemas']['pages_deployment'][]
          }
        }
      }
      /** @description Get deployments response failure. */
      '4XX': {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['pages_api-response-common-failure']
        }
      }
    }
  }
  'pages-deployment-create-deployment': {
    parameters: {
      query?: never
      header?: never
      path: {
        project_name: components['schemas']['pages_project_name']
        account_id: components['schemas']['pages_identifier']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': {
          /**
           * Format: binary
           * @description Headers configuration file for the deployment.
           */
          _headers?: string
          /**
           * Format: binary
           * @description Redirects configuration file for the deployment.
           */
          _redirects?: string
          /**
           * Format: binary
           * @description Routes configuration file defining routing rules.
           */
          '_routes.json'?: string
          /**
           * Format: binary
           * @description Worker bundle file in multipart/form-data format. Mutually exclusive with `_worker.js`.
           *     Cannot specify both `_worker.js` and `_worker.bundle` in the same request.
           *     Maximum size: 25 MiB.
           */
          '_worker.bundle'?: string
          /**
           * Format: binary
           * @description Worker JavaScript file. Mutually exclusive with `_worker.bundle`.
           *     Cannot specify both `_worker.js` and `_worker.bundle` in the same request.
           */
          '_worker.js'?: string
          /**
           * @description The branch to build the new deployment from. The `HEAD` of the branch will be used. If omitted, the production branch will be used by default.
           * @example staging
           */
          branch?: string
          /**
           * @description Boolean string indicating if the working directory has uncommitted changes.
           * @example false
           * @enum {string}
           */
          commit_dirty?: 'true' | 'false'
          /**
           * @description Git commit SHA associated with this deployment.
           * @example a1b2c3d4e5f6
           */
          commit_hash?: string
          /**
           * @description Git commit message associated with this deployment.
           * @example Update homepage
           */
          commit_message?: string
          /**
           * Format: binary
           * @description Functions routing configuration file.
           */
          'functions-filepath-routing-config.json'?: string
          /**
           * @description JSON string containing a manifest of files to deploy. Maps file paths to their content hashes.
           *     Required for direct upload deployments. Maximum 20,000 entries.
           * @example {"index.html": "abc123", "style.css": "def456"}
           */
          manifest?: string
          /**
           * @description The build output directory path.
           * @example dist
           */
          pages_build_output_dir?: string
          /** @description Hash of the Wrangler configuration file used for this deployment. */
          wrangler_config_hash?: string
        }
      }
    }
    responses: {
      /** @description Create deployment response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['pages_api-response-common'] & {
            result: components['schemas']['pages_deployment']
          }
        }
      }
      /** @description Create deployment response failure. */
      '4XX': {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['pages_api-response-common-failure']
        }
      }
    }
  }
  'pages-deployment-get-deployment-info': {
    parameters: {
      query?: never
      header?: never
      path: {
        deployment_id: components['schemas']['pages_identifier']
        project_name: components['schemas']['pages_project_name']
        account_id: components['schemas']['pages_identifier']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Get deployment info response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['pages_api-response-common'] & {
            result: components['schemas']['pages_deployment']
          }
        }
      }
      /** @description Get deployment info response failure. */
      '4XX': {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['pages_api-response-common-failure']
        }
      }
    }
  }
  'pages-deployment-delete-deployment': {
    parameters: {
      query?: {
        force?: boolean
      }
      header?: never
      path: {
        deployment_id: components['schemas']['pages_identifier']
        project_name: components['schemas']['pages_project_name']
        account_id: components['schemas']['pages_identifier']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Delete deployment response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['pages_api-response-common'] & {
            result: Record<string, never> | null
          }
        }
      }
      /** @description Delete deployment response failure. */
      '4XX': {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['pages_api-response-common-failure']
        }
      }
    }
  }
}
