# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: deploy delete
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy-delete-${{ github.head_ref || github.run_id }}

permissions: {}

jobs:
  deploy-delete:
    permissions:
      actions: read
      contents: read
      deployments: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          persist-credentials: false
      - id: 'cloudflare-pages'
        uses: ./delete
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
