# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: test
permissions:
  contents: read
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
  test:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-pnpm
      - name: Lint
        run: pnpm run lint --format=github
      - name: Typecheck
        run: pnpm run tsc:check
      - name: Test
        run: pnpm run test:ci
